apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  workspaces:
  - name: source
  steps:
  - name: build
    image: quay.io/buildah/stable:latest
    script: |
      buildah bud -t $(params.IMAGE) .
      buildah push $(params.IMAGE)
